feat: add expired report
dirtyg2120/thesis-backend pull request #42
Opened 2022-04-02 09:08 UTC by dirtyg2120

* Add `expired` to model
* Update `expired` to `True` if report is exist but not twitter user
* Generate new report (`expired=False`) if user exist and report is not

Problem: Can not have many report with the same primary key (`twitter_id`), so there are 2 ways:
1. Composite primary key (`id` and `created_at`)
2. Only update, no save snapshot

2022-04-02 09:13 UTC, phhai-hcmut commented on app/services/report.py
> +                expired=True if user is None else False,
```suggestion
                expired=user is None,
```

2022-04-02 09:46 UTC, dirtyg2120 commented on app/services/report.py
> +                expired=True if user is None else False,
oh :v okay

2022-04-03 03:11 UTC, produdez requested changes

2022-04-03 03:11 UTC, produdez commented on app/tests/test_report.py
>          pytest.skip("Will be fixed")
Finish the test when ur done

2022-04-03 03:13 UTC, produdez commented
Did you solve the problem mentioned in the PR description? I would go with composite keyl

2022-04-03 05:16 UTC, dirtyg2120 commented
> Did you solve the problem mentioned in the PR description? I would go with composite keyl

yea i did, the only problem left is currently cant have many records with the same primary key

2022-04-03 12:48 UTC, produdez commented
but we would want snapshot instead of overwrite?

2022-04-04 02:08 UTC, dirtyg2120 commented
i dunno the use of snapshot for now, but i think maybe we will need it later :V. I will go with the composite key

2022-04-04 02:13 UTC, produdez commented
We discussed that we want snapshot what are you talking about /(~_~)/

2022-04-04 02:19 UTC, dirtyg2120 commented
so why u put the "?" in there :V, i thought u ask

2022-04-04 02:23 UTC, produdez commented
Cause u seems clueless af and i'm trying to be subtle :v

2022-04-04 03:44 UTC, dirtyg2120 commented
Done for #31

2022-04-04 03:59 UTC, produdez approved these changes

2022-04-05 06:42 UTC, phhai-hcmut approved these changes

2022-04-05 09:01 UTC, merged